---
name: "bee"
namespace: "ethersphere"
version: "0.1.2"
readme: "README.md"
authors:
  - "devops (https://www.ethswarm.org/)"
description: Manage bee
license_file: "LICENSE"
tags:
  - bee
  - swarm
  - blockchain
  - decentralisation
  - storage
repository: "https://github.com/ethersphere/ansible-role-bee"
