---
- name: Add Bee repository.
  ansible.builtin.yum_repository:
    name: ethersphere
    description: Ethersphere Repo
    baseurl: "{{ bee_yum_repo_url }}"
    gpgcheck: true
    gpgkey: "{{ bee_yum_gpg_key }}"
